# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 11:21
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180125_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=''),
        ),
    ]
