# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 13:42
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180405_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
